Added PasswordAuthenticator Logic to CassandraConnector
maryvilledev/skilldirectory pull request #119
Opened 2017-01-04 21:09 UTC by Hopding

Fixed #116. Note that the username and password specified in the `make` file don't actually affect anything, because the current docker image that we are using does not specify an authenticator in the `cassandra.yml` file (I don't believe our image even has that file at all): https://docs.datastax.com/en/cassandra/2.1/cassandra/security/security_config_native_authenticate_t.html

2017-01-04 21:17 UTC, thebho requested changes

2017-01-04 21:17 UTC, thebho commented on data/cassandra.go
> +	logger.Printf("New Connector Path: %s, Port: %s, Keyspace: %s, "+
Lets not log the PW here.  Go ahead an add a debug log with the pw in the short term

2017-01-04 21:50 UTC, Hopding commented
Changes made 👍

2017-01-06 20:38 UTC, thebho approved these changes

2017-01-06 20:38 UTC, merged