Make File Now Accepts Multiple Flags
maryvilledev/skilldirectory pull request #121
Opened 2017-01-05 15:45 UTC by Hopding

Fixes #112.

2017-01-05 19:21 UTC, thebho commented
Just to be clear, this allows for a `--dropdata`, `--nodebug` or both flags and works as excepted?

2017-01-05 19:23 UTC, thebho requested changes

2017-01-05 19:23 UTC, thebho commented on make
> +if $debug_flag; then # Run with debug-level logging, unless "--nodebug" flag was used
Its better practice to have only one execute command.  This should still work if you do `./skilldirectory -debug=$debug_flag`

2017-01-05 22:47 UTC, Hopding commented on make
> +if $debug_flag; then # Run with debug-level logging, unless "--nodebug" flag was used
It does work that way, and looks much nicer too 👍

2017-01-05 22:48 UTC, Hopding commented
Correct. You can specify either flag or both, and it will work as expected either way.

2017-01-06 13:54 UTC, thebho approved these changes

2017-01-06 13:54 UTC, merged