Added Logic to Validate "skill_id" Field in Link POSTs
maryvilledev/skilldirectory pull request #125
Opened 2017-01-06 19:53 UTC by Hopding

Fixes #85.

2017-01-06 20:42 UTC, thebho requested changes
Needs some more testing

2017-01-06 21:35 UTC, Hopding commented
Need to write tests for the `validateLinkFields()` method. Also, look at adding tests for the `validateTMSkillFields()` method, because that seemed to slip through the review process for the PR that added it.

2017-01-09 14:35 UTC, Hopding commented
Tests added. Should be ready to merge 👍

2017-01-09 14:56 UTC, thebho approved these changes

2017-01-09 15:16 UTC, merged