Added necesary API endpoint
maryvilledev/skilldirectory pull request #156
Opened 2017-01-23 19:00 UTC by dane-johnson

Necessary endpoints for ui issue https://github.com/maryvilledev/skilldirectoryui/issues/75.

2017-01-23 19:15 UTC, Hopding approved these changes
Awesome 👍

2017-01-23 19:15 UTC, Hopding commented on controller/skillreviewscontroller.go
> +func (c *SkillReviewsController) getSkillReviewForSkill(skill_id string) error {
The name of this method confused me initially. I think changing the name to `getReviewsForSkill` (or `getSkillReviewsForSkill) would be more clear.

2017-01-23 22:06 UTC, dane-johnson commented
This one will need to be merged to have the reviews render properly.

2017-01-24 15:08 UTC, thebho requested changes

2017-01-24 15:08 UTC, thebho commented on controller/skillreviewscontroller.go
> +	opts := data.NewCassandraQueryOptions("skill_id", "'" + skill_id + "'", true)
Try this with false as the Id option.  If that doesn't work, I'll put this through and make a story about handling this kind of request

2017-01-24 16:58 UTC, thebho approved these changes

2017-01-24 16:58 UTC, merged