Added Postman tests
maryvilledev/skilldirectory pull request #164
Opened 2017-01-26 20:47 UTC by jdmaryville

Fixes #90

2017-01-26 21:26 UTC, solkaz requested changes

2017-01-26 21:26 UTC, solkaz commented on controller/skillreviewscontroller.go
> +	for idx := 0; idx < len(skillReviews); idx++ {
Could we not use a range for loop here?

2017-01-26 21:26 UTC, solkaz commented on controller/skillreviewscontroller.go
> +	return err
Should we not check for an error *before* we do a write?

2017-01-26 21:26 UTC, solkaz commented on controller/teammemberscontroller.go
> +
Shouldn't we check for an error?

2017-01-27 16:55 UTC, solkaz approved these changes

2017-01-27 19:20 UTC, thebho approved these changes

2017-01-27 19:20 UTC, merged