Issue27
maryvilledev/skilldirectory pull request #38
Opened 2016-12-09 22:26 UTC by Hopding

Fixes #27

2016-12-09 22:39 UTC, thebho requested changes
Add some tests to prove the filtering works

2016-12-12 14:08 UTC, thebho requested changes

2016-12-12 14:08 UTC, thebho commented on handler/skill_test.go
> +		fmt.Errorf("Did not expect error when getting skills with filter")
These should all be t.Errorf() then testing.  fmt.Errorf() creates a new error object with formatted text, but doesn't return it to the testing tool.

2016-12-12 14:08 UTC, thebho commented on handler/skills.go
> +extractSkillFilter() returns the filter value of the "skilltype" filter within
Again, I think this is probably overkill for comments, especially on a non-exported function.  I know by the function name what this does, and the logic and error messages are self explanatory.

2016-12-13 14:24 UTC, Hopding commented on handler/skill_test.go
> +		fmt.Errorf("Did not expect error when getting skills with filter")
Fixed

2016-12-13 14:25 UTC, Hopding commented on handler/skills.go
> +extractSkillFilter() returns the filter value of the "skilltype" filter within
I've removed the comments for `extractSkillFilter()`. Should be ready now 👍

2016-12-13 17:58 UTC, thebho commented
Looks good.  Does this work with the new Controllers in master?

2016-12-13 20:40 UTC, Hopding commented
It does now 😺

2016-12-13 21:58 UTC, thebho approved these changes

2016-12-13 22:07 UTC, merged