REST Endpoint for TeamMembers
maryvilledev/skilldirectory pull request #53
Opened 2016-12-16 14:33 UTC by Hopding

Fixes #16 and #17

2016-12-16 15:14 UTC, thebho approved these changes

2016-12-19 20:54 UTC, thebho requested changes

2016-12-19 20:54 UTC, thebho commented on controller/basecontroller.go
> -	if url.EscapedPath() != "/skills" && url.EscapedPath() != "/skills/" {
Let's extract this into another function.  The logic is already starting to get difficult to read.

2016-12-19 20:54 UTC, thebho commented on skilldirectoryschema.cql
> +CREATE INDEX IF NOT EXISTS ON skills2.teammembers ( title );
Please remove as discussed.

2016-12-19 21:28 UTC, thebho approved these changes

2016-12-19 21:28 UTC, thebho commented on controller/basecontroller.go
> +// isValidEndpoint() returns true if endpoint is an endpoint being
@Viper23 Will appreciate this change

2016-12-19 21:28 UTC, merged

2016-12-19 21:29 UTC, Hopding commented on controller/basecontroller.go
> +// isValidEndpoint() returns true if endpoint is an endpoint being
Who is @Viper23 ?